java_test(
    name = "example_test",
    srcs = glob(["*.java"]),
    test_class = "com.example.AppTest",
    deps = [
        "//src/app/src/main/java/com/example",
        "@maven//:junit_junit",
    ],
)
